name: BRIDGE-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old Docker cache
        run: |
          docker builder prune -af || true

      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache
          df -h

      # checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build image
      - name: Build BRIDGE Docker image
        run: |
          docker build --no-cache -t bridge_image .


      # Run CI tests inside container
      - name: Run tests inside BRIDGE container
        run: |
          docker run --rm bridge_image \
             conda run -n BRIDGE python -c "print('CI OK: ENV LOADED')"

      # Run main.py
      - name: Run main.py smoke test
        run: |
          docker run --rm bridge_image \
            conda run -n BRIDGE python main.py --help || true
